name: photo_viewer
description: 'Flutter image viewer library with multiple display modes. Features include: pinch-zoom, double-tap zoom, vertical dismiss, page navigation, custom overlays, and hero animations.'
version: 0.0.1
homepage: https://pub.dev/packages/photo_viewer

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
